
#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
# 

# Monitor Settings
monitor=eDP-1,2880x1800@60.00Hz,0x0,2

# ----------
#  Auto start & env
# ----------
exec-once = systemctl --user start hyprpolkitagent
exec-once = pypr & hypridle & agsv1 & hyprpaper & xdg-desktop-portal-gtk

# ----------
# Plugins
# ----------
source = ~/.config/hypr/conf/plugins.conf

# ----------
# Input
# ----------
source = ~/.config/hypr/conf/input.conf


# ----------
# General
# ----------
source = ~/.config/hypr/conf/general.conf

# ----------
# Decoration
# ----------
source = ~/.config/hypr/conf/decoration.conf

# ----------
# Animations
# ----------
source = ~/.config/hypr/conf/animations.conf

# ----------
# Keybinds
# ----------
source = ~/.config/hypr/conf/keybinds.conf

# ----------
# Dwindle
# ----------
source = ~/.config/hypr/conf/dwindle.conf

# ----------
# Gestures
# ----------
source = ~/.config/hypr/conf/gestures.conf

# ----------
# Rules
# ----------
source = ~/.config/hypr/conf/rules.conf
