# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

#set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"

set -g default-terminal "kitty" 
set-option -sa terminal-overrides ",alacritty*:Tc"
set-option -sa terminal-overrides ",kitty*:Tc"

# action key
unbind C-b
set-option -g prefix C-Space
set-option -g repeat-time 0
set-option -g focus-events on

set -g default-shell /bin/zsh

#### Key bindings

unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

set-window-option -g mode-keys vi

#bind t send-key C-t
# Reload settings
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

set -g mouse on
set-window-option -g mode-keys vi

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

# Mazimazing pane
bind -r m resize-pane -Z

#
#basic settings
set-option -g status-position top

set-window-option -g mode-keys vi

# look'n feel
set-option -g history-limit 64096

set -sg escape-time 10

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"

# Plugins settings
set -g @catppuccin_flavour 'mocha'
set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_show_path 0
set -g @tokyo-night-tmux_path_format relative
#set -g @tokyo-night-tmux_window_id_style dsquare
set -g @tokyo-night-tmux_show_git 0

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
