# ----------
# Keybinds
# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# ----------

$mainMod = SUPER
$ss = SUPER_SHIFT

# Plugin/Pyprland binds
bind = $mainMod, O, exec, pypr toggle tm
bind = $mainMod, P, exec, pypr toggle fm
bind = $mainMod, I, exec, pypr zoom

# MAINMODE
$mainMod = SUPER
$ss = SUPER_SHIFT

# Applications
bind = $mainMod, Return, exec, kitty
bind = $mainMod, B, exec, firefox
bind = $mainMod, N, exec, nautilus
bind = $ss, L, exec, hyprlock 
bind = $mainMod, Space, exec, tofi-drun | xargs hyprctl dispatch exec --

# Screenshot monitor
bind = , PRINT, exec, hyprshot -m output
# Screenshot a region
bind = $ss, PRINT, exec, hyprshot -m region
# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window

# Brightness Control Keybinds
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = , XF86MonBrightnessUp,   exec, brightnessctl set +5%

# Sound Control Keybinds
bind = , XF86AudioRaiseVolume,	exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume,	exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute,			exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86AudioMicMute,		exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
#bind = $mainMod,F,fullscreen
bind = $mainMod, q, killactive, 
bind = $ss, E, exit, 

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, h, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, l, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, k, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, j, movefocus, d

bind = $ss, h, resizeactive, -40 0
bind = $ss, l, resizeactive, 40 0
bind = $ss, k, resizeactive, 0 -40
bind = $ss, j, resizeactive, 0 40

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $ss, 1, movetoworkspace, 1
bind = $ss, 2, movetoworkspace, 2
bind = $ss, 3, movetoworkspace, 3
bind = $ss, 4, movetoworkspace, 4
bind = $ss, 5, movetoworkspace, 5
bind = $ss, 6, movetoworkspace, 6
bind = $ss, 7, movetoworkspace, 7
bind = $ss, 8, movetoworkspace, 8
bind = $ss, 9, movetoworkspace, 9
bind = $ss, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod,		mouse_down, workspace, e+1
bind = $mainMod,		mouse_up,	workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod,		mouse:272,	movewindow
